sonar.projectKey=campus-connect-key_campus-project
sonar.organization=campus-connect-key

sonar.sources=frontend,backend

sonar.exclusions=frontend/node_modules/**,frontend/dist/**,backend/venv/**,backend/__pycache__/**,backend/**/__pycache__/**,backend/.pytest_cache/**

sonar.sourceEncoding=UTF-8
