"""remove_clubs_and_add_team_id_to_registrations

Revision ID: 38aed26663ed
Revises: 658ade079d7b
Create Date: 2026-07-07 16:36:57.427935+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38aed26663ed'
down_revision: Union[str, None] = '658ade079d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizers_club_id'), table_name='organizers')
    op.drop_index(op.f('ix_organizers_organizer_id'), table_name='organizers')
    op.drop_index(op.f('ix_organizers_user_id'), table_name='organizers')
    op.drop_table('organizers')
    op.drop_index(op.f('ix_events_club_id'), table_name='events')
    op.drop_constraint(op.f('events_club_id_fkey'), 'events', type_='foreignkey')
    op.drop_column('events', 'club_id')
    op.drop_index(op.f('ix_clubs_club_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_college_id'), table_name='clubs')
    op.drop_table('clubs')
    op.add_column('registrations', sa.Column('team_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_registrations_team_id'), 'registrations', ['team_id'], unique=False)
    op.create_foreign_key(None, 'registrations', 'teams', ['team_id'], ['team_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_index(op.f('ix_registrations_team_id'), table_name='registrations')
    op.drop_column('registrations', 'team_id')
    op.add_column('events', sa.Column('club_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('events_club_id_fkey'), 'events', 'clubs', ['club_id'], ['club_id'], ondelete='SET NULL')
    op.create_index(op.f('ix_events_club_id'), 'events', ['club_id'], unique=False)
    op.create_table('clubs',
    sa.Column('club_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('college_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('club_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('faculty_incharge', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.college_id'], name=op.f('clubs_college_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('club_id', name=op.f('clubs_pkey'))
    )
    op.create_index(op.f('ix_clubs_college_id'), 'clubs', ['college_id'], unique=False)
    op.create_index(op.f('ix_clubs_club_id'), 'clubs', ['club_id'], unique=False)
    op.create_table('organizers',
    sa.Column('organizer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('club_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('designation', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], name=op.f('organizers_club_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('organizers_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organizer_id', name=op.f('organizers_pkey'))
    )
    op.create_index(op.f('ix_organizers_user_id'), 'organizers', ['user_id'], unique=True)
    op.create_index(op.f('ix_organizers_organizer_id'), 'organizers', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_organizers_club_id'), 'organizers', ['club_id'], unique=False)
    # ### end Alembic commands ###
