"""sync_schema

Revision ID: 986d2fe017ca
Revises: e624f7943d0b
Create Date: 2026-07-29 05:41:46.708633+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986d2fe017ca'
down_revision: Union[str, None] = 'e624f7943d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Events Table - Ensure all model fields exist in DB
    op.execute("""
        ALTER TABLE events ADD COLUMN IF NOT EXISTS fees NUMERIC(10, 2);
        ALTER TABLE events ADD COLUMN IF NOT EXISTS registered_fee NUMERIC(10, 2);
        ALTER TABLE events ADD COLUMN IF NOT EXISTS venue VARCHAR(500);
        ALTER TABLE events ADD COLUMN IF NOT EXISTS poster VARCHAR(500);
        ALTER TABLE events ADD COLUMN IF NOT EXISTS poster_url VARCHAR(500);
        ALTER TABLE events ADD COLUMN IF NOT EXISTS event_date DATE;
        ALTER TABLE events ADD COLUMN IF NOT EXISTS start_time TIME;
        ALTER TABLE events ADD COLUMN IF NOT EXISTS end_time TIME;
        ALTER TABLE events ADD COLUMN IF NOT EXISTS capacity INTEGER;
        ALTER TABLE events ADD COLUMN IF NOT EXISTS participation_type VARCHAR(50) DEFAULT 'individual';
        ALTER TABLE events ADD COLUMN IF NOT EXISTS reg_date_time TIMESTAMP;
        ALTER TABLE events ADD COLUMN IF NOT EXISTS rulebook_url VARCHAR(500);
        ALTER TABLE events ADD COLUMN IF NOT EXISTS schedule_url VARCHAR(500);
        ALTER TABLE events ADD COLUMN IF NOT EXISTS event_status VARCHAR(50);
        ALTER TABLE events ADD COLUMN IF NOT EXISTS category_id UUID;
        ALTER TABLE events ADD COLUMN IF NOT EXISTS rejection_reason TEXT;
    """)

    # Populate fees from registered_fee if fees is NULL
    op.execute("""
        UPDATE events SET fees = registered_fee WHERE fees IS NULL AND registered_fee IS NOT NULL;
    """)

    # 2. Users Table - Ensure ER & Profile columns exist
    op.execute("""
        ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR(255);
        ALTER TABLE users ADD COLUMN IF NOT EXISTS mobile VARCHAR(20);
        ALTER TABLE users ADD COLUMN IF NOT EXISTS college_name VARCHAR(255);
        ALTER TABLE users ADD COLUMN IF NOT EXISTS department VARCHAR(255);
        ALTER TABLE users ADD COLUMN IF NOT EXISTS course VARCHAR(255);
        ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image VARCHAR(500);
        ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(50);
        ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_code VARCHAR(6);
        ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_code_expires_at TIMESTAMP;
    """)

    # 3. User Profiles Table - Appearance settings
    op.execute("""
        ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS appearance_mode VARCHAR(20) DEFAULT 'system';
        ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS accent_color VARCHAR(20) DEFAULT 'indigo';
        ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS font_size VARCHAR(20) DEFAULT 'medium';
    """)

    # 4. Attendance Table - Venue, method, qrcode
    op.execute("""
        ALTER TABLE attendance ADD COLUMN IF NOT EXISTS qrcode_url VARCHAR(500);
        ALTER TABLE attendance ADD COLUMN IF NOT EXISTS attendance_method VARCHAR(100);
        ALTER TABLE attendance ADD COLUMN IF NOT EXISTS scanned_by UUID;
    """)

    # 5. Registrations Table
    op.execute("""
        ALTER TABLE registrations ADD COLUMN IF NOT EXISTS registration_type VARCHAR(100);
        ALTER TABLE registrations ADD COLUMN IF NOT EXISTS qr_code VARCHAR(500);
    """)

    # 6. Organizers Table
    op.execute("""
        ALTER TABLE organizers ADD COLUMN IF NOT EXISTS designation VARCHAR(255);
        ALTER TABLE organizers ADD COLUMN IF NOT EXISTS permissions TEXT;
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
