"""add_verification_code_and_expiry

Revision ID: cb66fd266a3f
Revises: 77ffa750631f
Create Date: 2026-07-14 06:15:28.948424+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb66fd266a3f'
down_revision: Union[str, None] = '77ffa750631f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_organizers_organizer_id'), 'organizers', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_organizers_user_id'), 'organizers', ['user_id'], unique=True)
    # ### end Alembic commands ###

    # Conditionally add verification columns to users table
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'verification_code' not in columns:
        op.add_column('users', sa.Column('verification_code', sa.String(length=6), nullable=True))
    if 'verification_code_expires_at' not in columns:
        op.add_column('users', sa.Column('verification_code_expires_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    # Conditionally remove verification columns from users table
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'verification_code' in columns:
        op.drop_column('users', 'verification_code')
    if 'verification_code_expires_at' in columns:
        op.drop_column('users', 'verification_code_expires_at')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizers_user_id'), table_name='organizers')
    op.drop_index(op.f('ix_organizers_organizer_id'), table_name='organizers')
    op.create_unique_constraint(op.f('uq_organizer_user'), 'organizers', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('organizers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
