"""align_schema_with_er

Revision ID: 658ade079d7b
Revises: a8c1e28fd296
Create Date: 2026-07-04 09:54:35.743086+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '658ade079d7b'
down_revision: Union[str, None] = 'a8c1e28fd296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_categories',
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_event_categories_category_id'), 'event_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_event_categories_category_name'), 'event_categories', ['category_name'], unique=True)
    op.create_table('feedback',
    sa.Column('feedback_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('participant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_feedback_event_id'), 'feedback', ['event_id'], unique=False)
    op.create_index(op.f('ix_feedback_feedback_id'), 'feedback', ['feedback_id'], unique=False)
    op.create_index(op.f('ix_feedback_participant_id'), 'feedback', ['participant_id'], unique=False)
    op.create_table('registrations',
    sa.Column('registration_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('participant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('registration_status', postgresql.ENUM('CONFIRMED', 'CANCELLED', 'WAITLISTED', 'ATTENDED', name='registrationstatus', create_type=False), nullable=False),
    sa.Column('payment_status', postgresql.ENUM('FREE', 'PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus', create_type=False), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('registration_type', sa.String(length=100), nullable=True),
    sa.Column('qr_code', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('registration_id'),
    sa.UniqueConstraint('event_id', 'participant_id', name='uq_event_participant_registration')
    )
    op.create_index(op.f('ix_registrations_event_id'), 'registrations', ['event_id'], unique=False)
    op.create_index(op.f('ix_registrations_participant_id'), 'registrations', ['participant_id'], unique=False)
    op.create_index(op.f('ix_registrations_registration_id'), 'registrations', ['registration_id'], unique=False)
    op.create_table('teams',
    sa.Column('team_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('leader_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=False),
    sa.Column('team_members', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leader_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index(op.f('ix_teams_event_id'), 'teams', ['event_id'], unique=False)
    op.create_index(op.f('ix_teams_leader_id'), 'teams', ['leader_id'], unique=False)
    op.create_index(op.f('ix_teams_team_id'), 'teams', ['team_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('registration_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_gateway', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_event_id'), 'payments', ['event_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payments_registration_id'), 'payments', ['registration_id'], unique=False)
    op.create_table('results',
    sa.Column('result_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('team_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('participant_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_results_event_id'), 'results', ['event_id'], unique=False)
    op.create_index(op.f('ix_results_participant_id'), 'results', ['participant_id'], unique=False)
    op.create_index(op.f('ix_results_result_id'), 'results', ['result_id'], unique=False)
    op.create_index(op.f('ix_results_team_id'), 'results', ['team_id'], unique=False)
    op.create_table('team_members',
    sa.Column('team_member_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('team_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('total_team_members', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_member_id')
    )
    op.create_index(op.f('ix_team_members_participant_id'), 'team_members', ['participant_id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_team_member_id'), 'team_members', ['team_member_id'], unique=False)
    op.drop_constraint(op.f('attendance_registration_id_fkey'), 'attendance', type_='foreignkey')
    op.drop_index(op.f('ix_event_registrations_event_id'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_registration_id'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_user_id'), table_name='event_registrations')
    op.drop_table('event_registrations')
    op.add_column('attendance', sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False))
    op.add_column('attendance', sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False))
    op.add_column('attendance', sa.Column('qrcode_url', sa.String(length=500), nullable=True))
    op.add_column('attendance', sa.Column('attendance_method', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_attendance_event_id'), 'attendance', ['event_id'], unique=False)
    op.create_index(op.f('ix_attendance_user_id'), 'attendance', ['user_id'], unique=False)
    op.create_foreign_key(None, 'attendance', 'registrations', ['registration_id'], ['registration_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'attendance', 'events', ['event_id'], ['event_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'attendance', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.add_column('certificates', sa.Column('registration_id', sa.UUID(as_uuid=False), nullable=False))
    op.add_column('certificates', sa.Column('participant_id', sa.UUID(as_uuid=False), nullable=False))
    op.add_column('certificates', sa.Column('certificate_type', sa.String(length=100), nullable=True))
    op.add_column('certificates', sa.Column('certificate_url', sa.String(length=500), nullable=True))
    op.add_column('certificates', sa.Column('issue_date', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_certificates_user_id'), table_name='certificates')
    op.create_index(op.f('ix_certificates_participant_id'), 'certificates', ['participant_id'], unique=False)
    op.create_index(op.f('ix_certificates_registration_id'), 'certificates', ['registration_id'], unique=False)
    op.drop_constraint(op.f('certificates_user_id_fkey'), 'certificates', type_='foreignkey')
    op.create_foreign_key(None, 'certificates', 'registrations', ['registration_id'], ['registration_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'certificates', 'users', ['participant_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('certificates', 'user_id')
    op.add_column('events', sa.Column('category_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('events', sa.Column('event_date', sa.Date(), nullable=True))
    op.add_column('events', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('events', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('events', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('registered_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('events', sa.Column('poster_url', sa.String(length=500), nullable=True))
    op.add_column('events', sa.Column('rulebook_url', sa.String(length=500), nullable=True))
    op.add_column('events', sa.Column('schedule_url', sa.String(length=500), nullable=True))
    op.add_column('events', sa.Column('event_status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_events_category_id'), 'events', ['category_id'], unique=False)
    op.drop_constraint(op.f('events_organizer_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'event_categories', ['category_id'], ['category_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'events', 'users', ['organizer_id'], ['user_id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mobile', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('college_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('course', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'profile_image')
    op.drop_column('users', 'course')
    op.drop_column('users', 'department')
    op.drop_column('users', 'college_name')
    op.drop_column('users', 'mobile')
    op.drop_column('users', 'full_name')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_organizer_id_fkey'), 'events', 'organizers', ['organizer_id'], ['organizer_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_events_category_id'), table_name='events')
    op.drop_column('events', 'event_status')
    op.drop_column('events', 'schedule_url')
    op.drop_column('events', 'rulebook_url')
    op.drop_column('events', 'poster_url')
    op.drop_column('events', 'registered_fee')
    op.drop_column('events', 'capacity')
    op.drop_column('events', 'end_time')
    op.drop_column('events', 'start_time')
    op.drop_column('events', 'event_date')
    op.drop_column('events', 'category_id')
    op.add_column('certificates', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.create_foreign_key(op.f('certificates_user_id_fkey'), 'certificates', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_certificates_registration_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_participant_id'), table_name='certificates')
    op.create_index(op.f('ix_certificates_user_id'), 'certificates', ['user_id'], unique=False)
    op.drop_column('certificates', 'issue_date')
    op.drop_column('certificates', 'certificate_url')
    op.drop_column('certificates', 'certificate_type')
    op.drop_column('certificates', 'participant_id')
    op.drop_column('certificates', 'registration_id')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_registration_id_fkey'), 'attendance', 'event_registrations', ['registration_id'], ['registration_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_attendance_user_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_event_id'), table_name='attendance')
    op.drop_column('attendance', 'attendance_method')
    op.drop_column('attendance', 'qrcode_url')
    op.drop_column('attendance', 'event_id')
    op.drop_column('attendance', 'user_id')
    op.create_table('event_registrations',
    sa.Column('registration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('registration_status', postgresql.ENUM('CONFIRMED', 'CANCELLED', 'WAITLISTED', 'ATTENDED', name='registrationstatus'), autoincrement=False, nullable=False),
    sa.Column('payment_status', postgresql.ENUM('FREE', 'PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), autoincrement=False, nullable=False),
    sa.Column('registered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], name=op.f('event_registrations_event_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('event_registrations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('registration_id', name=op.f('event_registrations_pkey')),
    sa.UniqueConstraint('event_id', 'user_id', name=op.f('uq_event_user_registration'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_event_registrations_user_id'), 'event_registrations', ['user_id'], unique=False)
    op.create_index(op.f('ix_event_registrations_registration_id'), 'event_registrations', ['registration_id'], unique=False)
    op.create_index(op.f('ix_event_registrations_event_id'), 'event_registrations', ['event_id'], unique=False)
    op.drop_index(op.f('ix_team_members_team_member_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_participant_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_results_team_id'), table_name='results')
    op.drop_index(op.f('ix_results_result_id'), table_name='results')
    op.drop_index(op.f('ix_results_participant_id'), table_name='results')
    op.drop_index(op.f('ix_results_event_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_payments_registration_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_event_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_teams_team_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_leader_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_event_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_registrations_registration_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_participant_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_event_id'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_index(op.f('ix_feedback_participant_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_event_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_event_categories_category_name'), table_name='event_categories')
    op.drop_index(op.f('ix_event_categories_category_id'), table_name='event_categories')
    op.drop_table('event_categories')
    # ### end Alembic commands ###
